gui:
  authorColors:
    'darianmorat': 'blue'
    '*': 'magenta'
  border: single
  showBottomLine: false
  # showPanelJumps: false
  theme:
    # activeBorderColor:
    #   - white
    #   - bold
    selectedLineBgColor:
      - "#303030"
      - bold
customCommands:
  - key: "w"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
